### ISSUE TITLE
No module named 'flit.inifile'

### ISSUE THREAD

**Issue by ashprice** [datapane/datapane#177]
### System Information
- OS: Arch Linux 5.15.8-arch1-1
- Python version: 3.10.1
- Python environment: pip
- Using jupyter: false
- Datapane version: 0.3.8

### Bug / Issue
When running `datapane hello-world` or running a previously working project involving the datapane library I am getting the following error:
```
Traceback (most recent call last):
  File "/home/hearth/.local/bin/datapane", line 5, in <module>
    from datapane.__main__ import main
  File "/home/hearth/.local/lib/python3.10/site-packages/datapane/__init__.py", line 2, in <module>
    from .api import (  # noqa: F401
  File "/home/hearth/.local/lib/python3.10/site-packages/datapane/api.py", line 37, in <module>
    from dp_common.scripts.config import DATAPANE_YAML, DatapaneCfg
  File "/home/hearth/.local/lib/python3.10/site-packages/dp_common/scripts/__init__.py", line 2, in <module>
    from .builder import build_local_sdist, build_wheel
  File "/home/hearth/.local/lib/python3.10/site-packages/dp_common/scripts/builder.py", line 15, in <module>
    from flit.inifile import ConfigError, read_flit_config
ModuleNotFoundError: No module named 'flit.inifile'

```

I have tried reinstalling flit both with my system's package manager, pip, and by cloning the flit git repo; I also played around with the commands used to install from source. I've had a look at builder.py and tried reinstalling stuff with pipenv, but no dice.

**Comment by mands** [comment]
Hi @ashprice ,

Thanks for raising this (and apologies for the delay) - I think this may be due to a using an old version of Datapane `0.3.8`, when the current is `0.13.2`. Can you please try updating your version of the `datapane` package and trying again?
