### ISSUE TITLE
Getting ImportError for 'json_item' when running dp.Plot in the Datapane demo script

### ISSUE THREAD

**Issue by dreme** [datapane/datapane#97]
### System Information
- OS: Win 10
- Python version: 3.8.8
- Python environment: conda
- Error occurs when running the script in JupyterLab or Spyder
- Datapane version: 0.10.3

### Bug / Issue
Getting ImportError for 'json_item' when running dp.Plot in the Datapane demo script

Here is the script:
```
import altair as alt
import pandas as pd
import datapane as dp
from datetime import date

# Sign-in with your unique token
dp.login(token="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

dataset = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')
locations = dataset[['location', 'iso_code']].sample(3) # Replace with you own locations to customize!
df = dataset[dataset.iso_code.isin(locations.iso_code)]

plot = alt.Chart(df).mark_area(opacity=0.4, stroke='black').encode(
    x='date:T', y=alt.Y('new_cases_smoothed_per_million:Q', stack=None),
    color=alt.Color('location:N', scale=alt.Scale(scheme='set1')), tooltip='location:N'
).interactive().properties(width='container')

# Create report
r = dp.Report(
    f'### Comparing COVID cases in {", ".join(locations.location)}',
    f'_Built using data from [Our World in Data](https://ourworldindata.org/) on {date.today()}_',
    dp.Plot(plot),
    dp.DataTable(df),
)

# Publish
r.publish(name=f'COVID-19 in {" ".join(locations.iso_code)}', open=True, description=f'COVID-19 in {", ".join(locations.location)}')
```
Here is the error traceback:
```
Connected successfully to https://datapane.com as dreme
Traceback (most recent call last):

  File "C:\Users\emeau\OneDrive\IT\Python\Scripts\Datapane demo.py", line 30, in <module>
    dp.Plot(plot),

  File "C:\Users\emeau\anaconda3\envs\py38\lib\site-packages\datapane\client\api\report\blocks.py", line 642, in __init__
    out_fn = self._save_obj(data, as_json=False)

  File "C:\Users\emeau\anaconda3\envs\py38\lib\site-packages\datapane\client\api\report\blocks.py", line 578, in _save_obj
    from ..files import save

  File "C:\Users\emeau\anaconda3\envs\py38\lib\site-packages\datapane\client\api\files.py", line 20, in <module>
    from .files_optional import Axes, BFigure, BLayout, Figure, Map, PFigure, json_item

ImportError: cannot import name 'json_item' from 'datapane.client.api.files_optional' (C:\Users\emeau\anaconda3\envs\py38\lib\site-packages\datapane\client\api\files_optional.py)
```

Here is a conda list of the python modules in the env
```
(py38) C:\Users\emeau>conda list
# packages in environment at C:\Users\emeau\anaconda3\envs\py38:
#
# Name                    Version                   Build  Channel
abseil-cpp                20200923.3           h0e60522_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
altair                    4.1.0                      py_1    conda-forge
anyio                     2.2.0            py38haa244fe_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
arrow-cpp                 3.0.0           py38had945b9_9_cpu    conda-forge
astroid                   2.5.1            py38haa244fe_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
autopep8                  1.5.6              pyhd8ed1ab_0    conda-forge
aws-c-cal                 0.4.5                hd123ed8_8    conda-forge
aws-c-common              0.5.2                h8ffe710_0    conda-forge
aws-c-event-stream        0.2.7                h828c5a6_1    conda-forge
aws-c-io                  0.9.1                h92767cf_1    conda-forge
aws-checksums             0.1.11               h92767cf_3    conda-forge
aws-sdk-cpp               1.8.151              ha9f9437_1    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py38h294d835_1    conda-forge
black                     20.8b1                     py_1    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
boltons                   20.2.1             pyh9f0ad1d_0    conda-forge
brotli                    1.0.9                h0e60522_4    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-ares                    1.17.1               h8ffe710_1    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.5           py38hd8c33c5_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-spinner             0.1.10             pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorlog                  4.7.2            py38haa244fe_0    conda-forge
confuse                   1.4.0              pyhd3deb0d_0    conda-forge
cryptography              3.4.6            py38hd7da0ea_0    conda-forge
curl                      7.75.0               hf1763fc_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dacite                    1.6.0              pyhd3deb0d_0    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
datapane                  0.10.3             pyhd8ed1ab_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.16             py38haa244fe_3    conda-forge
dominate                  2.4.0                      py_0    conda-forge
double-conversion         3.1.5                h6538335_2    conda-forge
eigen                     3.3.9                h2d74725_1    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.10               h39d44d4_0    conda-forge
face                      20.1.1                     py_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
flake8                    3.8.4                      py_0    conda-forge
flit-core                 3.0.0                      py_1    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
furl                      2.1.0                      py_0    conda-forge
future                    0.18.2           py38haa244fe_3    conda-forge
gflags                    2.2.2             ha925a31_1004    conda-forge
gl2ps                     1.4.2                h0597ee9_0    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
glob2                     0.7                        py_0    conda-forge
glog                      0.4.0                h0174b99_3    conda-forge
glom                      20.11.0            pyhd3deb0d_0    conda-forge
grpc-cpp                  1.36.4               hd4140ee_0    conda-forge
hdf4                      4.2.13            h0e5069d_1004    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
helpdev                   0.7.1              pyhd8ed1ab_0    conda-forge
htmlmin                   0.1.12                     py_1    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagehash                 4.2.0              pyhd8ed1ab_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.7.3            py38haa244fe_0    conda-forge
importlib_metadata        3.7.3                hd8ed1ab_0    conda-forge
importlib_resources       5.1.2            py38haa244fe_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipyevents                 0.8.2              pyhd8ed1ab_0    conda-forge
ipykernel                 5.5.0            py38hc5df569_1    conda-forge
ipympl                    0.6.3              pyhd8ed1ab_0    conda-forge
ipython                   7.21.0           py38hc5df569_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
isort                     5.8.0              pyhd8ed1ab_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.2           py38haa244fe_1    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsoncpp                   1.9.4                h2d74725_1    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter-packaging         0.7.12             pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyter_highlight_selected_word 0.2.0           py38haa244fe_1002    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1            py38haa244fe_2    conda-forge
jupyter_server            1.4.1            py38haa244fe_0    conda-forge
jupyterlab                3.0.12             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
keyring                   23.0.0           py38haa244fe_0    conda-forge
kiwisolver                1.3.1            py38hbd9d945_1    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
lazy-object-proxy         1.5.2            py38h294d835_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_0    conda-forge
libcurl                   7.75.0               hf1763fc_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.1                 h4f54205_2    conda-forge
libprotobuf               3.15.6               h7755175_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_3    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtheora                 1.1.1             h62dcd97_1004    conda-forge
libthrift                 0.14.1               h636ae23_1    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
libutf8proc               2.6.1                hcb41399_0    conda-forge
libxml2                   2.9.10               hf5bbc77_3    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
llvmlite                  0.36.0           py38h57a6900_0    conda-forge
loguru                    0.5.3            py38h32f6830_2    conda-forge
lxml                      4.6.2            py38h292cb97_1    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                1.1.1            py38h294d835_3    conda-forge
matplotlib                3.3.4            py38haa244fe_0    conda-forge
matplotlib-base           3.3.4            py38h34ddff4_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
micawber                  0.5.2              pyhd8ed1ab_0    conda-forge
missingno                 0.4.2                      py_1    conda-forge
mistune                   0.8.4           py38h294d835_1003    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mock                      4.0.3            py38haa244fe_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
mypy_extensions           0.4.3            py38haa244fe_3    conda-forge
nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38haa244fe_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
networkx                  2.5                        py_0    conda-forge
nodejs                    15.12.0              h57928b3_0    conda-forge
notebook                  6.2.0            py38haa244fe_0    conda-forge
numba                     0.53.0           py38h5c177ec_1    conda-forge
numexpr                   2.7.3            py38h4c96930_0    conda-forge
numpy                     1.20.1           py38h0cc643e_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openpyxl                  3.0.7              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
orderedmultidict          1.0.1                      py_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.3            py38h4c96930_0    conda-forge
pandas-datareader         0.9.0              pyh44b312d_0    conda-forge
pandas-profiling          2.11.0             pyhd8ed1ab_0    conda-forge
pandoc                    2.12                 h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
phik                      0.11.2             pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.2            py38h9273828_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pivottablejs              0.9.0            py38haa95532_0
pluggy                    0.13.1           py38haa244fe_4    conda-forge
proj                      7.2.0                h1cfcee9_2    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.17             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h294d835_1    conda-forge
psycopg2                  2.8.6            py38hd8c33c5_2    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pugixml                   1.11.4               h0e60522_0    conda-forge
pyarrow                   3.0.0           py38ha37a76c_9_cpu    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                6.0.0              pyhd8ed1ab_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pylint                    2.7.2            py38haa244fe_0    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.2              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py38h31c79cd_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
pytables                  3.6.1            py38h153c448_3    conda-forge
python                    3.8.8           h7840368_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytoml                    0.1.21                     py_0    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py38h347fdf6_3    conda-forge
pywin32                   300              py38h294d835_0    conda-forge
pywin32-ctypes            0.2.0           py38haa244fe_1003    conda-forge
pywinpty                  0.5.7            py38h32f6830_1    conda-forge
pyyaml                    5.4.1            py38h294d835_0    conda-forge
pyzmq                     22.0.3           py38h09162b1_1    conda-forge
qdarkstyle                2.8.1              pyhd8ed1ab_2    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.3              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
re2                       2020.11.01           h0e60522_0    conda-forge
regex                     2021.3.17        py38h294d835_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.7            py38h8b54edf_1    conda-forge
scipy                     1.6.1            py38h5f893b4_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
sniffio                   1.2.0            py38haa244fe_1    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.5.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.2.3            py38haa244fe_0    conda-forge
spyder-kernels            1.10.2           py38haa244fe_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
statsmodels               0.12.2           py38h347fdf6_0    conda-forge
stringcase                1.2.0                      py_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tangled-up-in-unicode     0.0.7              pyhd8ed1ab_0    conda-forge
tbb                       2020.2               h2d74725_4    conda-forge
tbb-devel                 2020.2               h2d74725_4    conda-forge
terminado                 0.9.3            py38haa244fe_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
textdistance              4.2.1              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.2            py38h294d835_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
ujson                     4.0.2            py38h885f38d_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
utfcpp                    3.1.2                         0    conda-forge
validators                0.18.2             pyhd3deb0d_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
visions                   0.6.0              pyh9f0ad1d_0    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
vtk                       9.0.1           no_osmesa_py38h3499093_104    conda-forge
watchdog                  1.0.2            py38haa244fe_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py38haa244fe_4    conda-forge
win32_setctime            1.0.3                      py_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1           py38h294d835_3    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge

```

**Comment by mands** [comment]
Thanks for raising - we've just released 0.10.4 on pip and conda that resolves the issue

**Comment by dreme** [comment]
And thanks for the quick response @mands !

I can now run the script successfully and it opens up  the **COVID-19 in Montenegro, Cyprus, Mozambique** page.

However, when I click the `Pandas Profiling` button all I get is the following error: `{"error": "Server Error (500)"}` at this page: 
https://datapane.com/u/dreme/reports/covid-19-in-mne-cyp-moz/extensions/pandas-profiling/50ce9526f0b4764d118ed4718e6a260c4a39c552056f296c65dca07804b51de2/

**Comment by mands** [comment]
Yes, we'll be releasing a fix for this early next week - thanks for the update!
